version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: PoGoMITM.sln
  verbosity: minimal
artifacts:
- path: Release.zip
  name: Release
on_success:
- cmd: 7z a Release.zip %APPVEYOR_BUILD_FOLDER%\PoGoMITM.Launcher\bin\Release\*.*
