// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Networking.Platform.Requests.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Platform.Requests {

  /// <summary>Holder for reflection information generated from POGOProtos.Networking.Platform.Requests.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class POGOProtosNetworkingPlatformRequestsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos.Networking.Platform.Requests.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static POGOProtosNetworkingPlatformRequestsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUGxhdGZvcm0uUmVxdWVzdHMucHJv",
            "dG8SJ1BPR09Qcm90b3MuTmV0d29ya2luZy5QbGF0Zm9ybS5SZXF1ZXN0cyIw",
            "ChVCdXlJdGVtQW5kcm9pZFJlcXVlc3QSFwoPYnV5X2l0ZW1faW50ZW50GAEg",
            "ASgJIioKF0J1eUl0ZW1Qb2tlQ29pbnNSZXF1ZXN0Eg8KB2l0ZW1faWQYASAB",
            "KAkiPAodU2VuZEVuY3J5cHRlZFNpZ25hdHVyZVJlcXVlc3QSGwoTZW5jcnlw",
            "dGVkX3NpZ25hdHVyZRgBIAEoDGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest), global::POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest.Parser, new[]{ "BuyItemIntent" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest), global::POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest.Parser, new[]{ "ItemId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest), global::POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest.Parser, new[]{ "EncryptedSignature" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class BuyItemAndroidRequest : pb::IMessage<BuyItemAndroidRequest> {
    private static readonly pb::MessageParser<BuyItemAndroidRequest> _parser = new pb::MessageParser<BuyItemAndroidRequest>(() => new BuyItemAndroidRequest());
    public static pb::MessageParser<BuyItemAndroidRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Platform.Requests.POGOProtosNetworkingPlatformRequestsReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public BuyItemAndroidRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public BuyItemAndroidRequest(BuyItemAndroidRequest other) : this() {
      buyItemIntent_ = other.buyItemIntent_;
    }

    public BuyItemAndroidRequest Clone() {
      return new BuyItemAndroidRequest(this);
    }

    /// <summary>Field number for the "buy_item_intent" field.</summary>
    public const int BuyItemIntentFieldNumber = 1;
    private string buyItemIntent_ = "";
    /// <summary>
    ///  see https://developer.android.com/google/play/billing/billing_reference.html table 4
    /// </summary>
    public string BuyItemIntent {
      get { return buyItemIntent_; }
      set {
        buyItemIntent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as BuyItemAndroidRequest);
    }

    public bool Equals(BuyItemAndroidRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BuyItemIntent != other.BuyItemIntent) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (BuyItemIntent.Length != 0) hash ^= BuyItemIntent.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (BuyItemIntent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BuyItemIntent);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (BuyItemIntent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuyItemIntent);
      }
      return size;
    }

    public void MergeFrom(BuyItemAndroidRequest other) {
      if (other == null) {
        return;
      }
      if (other.BuyItemIntent.Length != 0) {
        BuyItemIntent = other.BuyItemIntent;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            BuyItemIntent = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class BuyItemPokeCoinsRequest : pb::IMessage<BuyItemPokeCoinsRequest> {
    private static readonly pb::MessageParser<BuyItemPokeCoinsRequest> _parser = new pb::MessageParser<BuyItemPokeCoinsRequest>(() => new BuyItemPokeCoinsRequest());
    public static pb::MessageParser<BuyItemPokeCoinsRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Platform.Requests.POGOProtosNetworkingPlatformRequestsReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public BuyItemPokeCoinsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public BuyItemPokeCoinsRequest(BuyItemPokeCoinsRequest other) : this() {
      itemId_ = other.itemId_;
    }

    public BuyItemPokeCoinsRequest Clone() {
      return new BuyItemPokeCoinsRequest(this);
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 1;
    private string itemId_ = "";
    public string ItemId {
      get { return itemId_; }
      set {
        itemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as BuyItemPokeCoinsRequest);
    }

    public bool Equals(BuyItemPokeCoinsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemId != other.ItemId) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (ItemId.Length != 0) hash ^= ItemId.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ItemId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (ItemId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemId);
      }
      return size;
    }

    public void MergeFrom(BuyItemPokeCoinsRequest other) {
      if (other == null) {
        return;
      }
      if (other.ItemId.Length != 0) {
        ItemId = other.ItemId;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ItemId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class SendEncryptedSignatureRequest : pb::IMessage<SendEncryptedSignatureRequest> {
    private static readonly pb::MessageParser<SendEncryptedSignatureRequest> _parser = new pb::MessageParser<SendEncryptedSignatureRequest>(() => new SendEncryptedSignatureRequest());
    public static pb::MessageParser<SendEncryptedSignatureRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Platform.Requests.POGOProtosNetworkingPlatformRequestsReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public SendEncryptedSignatureRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public SendEncryptedSignatureRequest(SendEncryptedSignatureRequest other) : this() {
      encryptedSignature_ = other.encryptedSignature_;
    }

    public SendEncryptedSignatureRequest Clone() {
      return new SendEncryptedSignatureRequest(this);
    }

    /// <summary>Field number for the "encrypted_signature" field.</summary>
    public const int EncryptedSignatureFieldNumber = 1;
    private pb::ByteString encryptedSignature_ = pb::ByteString.Empty;
    public pb::ByteString EncryptedSignature {
      get { return encryptedSignature_; }
      set {
        encryptedSignature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as SendEncryptedSignatureRequest);
    }

    public bool Equals(SendEncryptedSignatureRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EncryptedSignature != other.EncryptedSignature) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (EncryptedSignature.Length != 0) hash ^= EncryptedSignature.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (EncryptedSignature.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(EncryptedSignature);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (EncryptedSignature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EncryptedSignature);
      }
      return size;
    }

    public void MergeFrom(SendEncryptedSignatureRequest other) {
      if (other == null) {
        return;
      }
      if (other.EncryptedSignature.Length != 0) {
        EncryptedSignature = other.EncryptedSignature;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            EncryptedSignature = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
