// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Networking.Platform.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Platform {

  /// <summary>Holder for reflection information generated from POGOProtos.Networking.Platform.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class POGOProtosNetworkingPlatformReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos.Networking.Platform.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static POGOProtosNetworkingPlatformReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRQT0dPUHJvdG9zLk5ldHdvcmtpbmcuUGxhdGZvcm0ucHJvdG8SHlBPR09Q",
            "cm90b3MuTmV0d29ya2luZy5QbGF0Zm9ybSqaAQoTUGxhdGZvcm1SZXF1ZXN0",
            "VHlwZRIQCgxNRVRIT0RfVU5TRVQQABIWChJCVVlfSVRFTV9QT0tFQ09JTlMQ",
            "AhIUChBCVVlfSVRFTV9BTkRST0lEEAMSEAoMQlVZX0lURU1fSU9TEAQSEwoP",
            "R0VUX1NUT1JFX0lURU1TEAUSHAoYU0VORF9FTkNSWVBURURfU0lHTkFUVVJF",
            "EAZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Networking.Platform.PlatformRequestType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PlatformRequestType {
    [pbr::OriginalName("METHOD_UNSET")] MethodUnset = 0,
    [pbr::OriginalName("BUY_ITEM_POKECOINS")] BuyItemPokecoins = 2,
    [pbr::OriginalName("BUY_ITEM_ANDROID")] BuyItemAndroid = 3,
    [pbr::OriginalName("BUY_ITEM_IOS")] BuyItemIos = 4,
    [pbr::OriginalName("GET_STORE_ITEMS")] GetStoreItems = 5,
    [pbr::OriginalName("SEND_ENCRYPTED_SIGNATURE")] SendEncryptedSignature = 6,
  }

  #endregion

}

#endregion Designer generated code
